### ISSUE TITLE
Cant pass context object thru routes. The method 'setOverlayVisible' was called on null.

### ISSUE THREAD

**Issue by kitchanismo** [rodrigobastosv/loading_overlay#1]
class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.teal, fontFamily: 'Baloo'),
      initialRoute: '/',
      routes: {
        '/': (context) => LoaderOverlay(useDefaultLoading: true, child: Home()),
        '/preview': (context) => Preview(),
        '/add': (context) => AddForm(),
        '/signin': (context) => SignIn(),
        '/found': (context) => Found(),
        '/scanner': (context) => Scanner(title: 'Scanner'),
      },
    );
  }
}

**Comment by swapsy2018** [comment]
the same problem I've met. Does anyone give a solution? thanks

**Comment by rodrigobastosv** [comment]
Hi guys, first of all thanks for using this package.

This package was not originally designed to work with named routes, but of course it should work with it.

I'm back after some time off. Give me a day and you will have a correction for that.

Stay tuned and thanks again

**Comment by rodrigobastosv** [comment]
Ok guys, it was easy to catch the error.

I just created a new widget GlobalLoaderOverlay to use on named routes. Just wrap your MaterialApp with GlobalLoaderOverlay and you would be good to go. It has the same features of LoaderOverlay.

This change will be on the 1.1.0 version of the package. I've already uploaded.

Thanks again for the feedback
