### ISSUE TITLE
New update lets the user interact with the screen while it's loading

### ISSUE THREAD

**Issue by blck-shp** [rodrigobastosv/loading_overlay#10]
I updated the package to the latest version (1.2.0) when I noticed that the whole screen isn't opaqued. I'm using the SpinKit loader on top of this loading_overlay package and since the SpinKit loader has a default size of 50.0 pixels, the container widget apparently adjusted to the minimum size, showing a long horizontal grey line at the center with a SpinKit loader on it.

Now, I reverted back to the last version that I used (1.1.1) and it's working. I'm not sure if there's any additional changes that I need to make.

```
     GlobalLoaderOverlay(
      useDefaultLoading: false,
      overlayWidget: Container(
        color: Colors.grey,
        child: Center(child: SpinKitThreeBounce(color: Color(0xff000000)),),
      ),
     ),
```

**Comment by rodrigobastosv** [comment]
Hi @blck-shp , thanks for using this package! 

Your container is taking the hole horizontal width.

I believe you can achieve the desired result with the above code:

```
GlobalLoaderOverlay(
        overlayColor: Colors.grey,
        overlayOpacity: 0.6,
        useDefaultLoading: false,
        overlayWidget: Center(
          child: SpinKitThreeBounce(
            color: Color(0xff000000),
          ),
        )
```
Just drop the Container widget, and you can set the overlayColor and overlayOpacity parameters to set the desired color and opacity.

I'll leave this issue open for now. Feel free to give feedback if it helps you or not.

Thanks!

**Comment by blck-shp** [comment]
Hi @rodrigobastosv , thanks for the response. It's working now.
