### ISSUE TITLE
Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by TempusZA** [rodrigobastosv/loading_overlay#12]
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure>
package:flutter/…/widgets/framework.dart:3936
#1      Element._debugCheckStateIsActiveForAncestorLookup
package:flutter/…/widgets/framework.dart:3950
#2      Element.findAncestorWidgetOfExactType
package:flutter/…/widgets/framework.dart:3989
#3      OverlayControllerWidget.of
package:loader_overlay/src/overlay_controller_widget.dart:10
#4      OverlayControllerWidgetExtension.getOverlayController
package:loader_overlay/src/overlay_controller_widget_extension.dart:8
...

**Comment by rodrigobastosv** [comment]
Hi @TempusZA , thanks for using this package.

Can you provide a small sample with the error?

**Comment by TempusZA** [comment]
sure. The app design I am using here differs from your pub.dev example. 
To see the error, simply run the app, and press "Login". 
https://github.com/TempusZA/Overlay_error

**Comment by rodrigobastosv** [comment]
Hi @TempusZA , i analised this error.

The LoaderOverlay widget was created to be used only once in the widget tree. Due to the structure it was created, it will not work using more than one LoaderOverlay. You can check the README for a general use.

The good news is that a LoaderOverlay is enough to do what you need.

I made the correction in your code, if you can give me permission to upload the changes to a branch for you to analyze.

**Comment by TempusZA** [comment]
Hi @rodrigobastosv , thanks for the feedback. I was not aware of this. 

If you create a pull request into master, I should be able to view the code changes ?

**Comment by rodrigobastosv** [comment]
I tried but got permission denied error.

Could you add me as contributor of the project?

**Comment by TempusZA** [comment]
its a public repo, with no PR rules associated to it ? Not sure how to add you as an explicit collaborator ? Did you try the Overlay_rework branch ? 
If you dont come right, could you create zip the folder and send it to me on WeTransfer ? email address is administrator@tempus.ink

**Comment by rodrigobastosv** [comment]
That's strange.

But you can get the project from here: https://drive.google.com/file/d/1acs-regJGvJ9hHJmiiNfB3ExiynlHOxg/view?usp=sharing

**Comment by rodrigobastosv** [comment]
Hey @TempusZA , did it work to resolve the mentioned error? If you have not resolved, do not hesitate to ask for help.

It will be my pleasure.
