### ISSUE TITLE
Example for global loading overlay

### ISSUE THREAD

**Issue by nissim-dev** [rodrigobastosv/loading_overlay#14]
Could you set up and example on how to use the GlobalLoaderOverlay widget.

`context.loaderOverlay` isn't configured

and i cannot use it.

**Comment by rodrigovasconceloszup** [comment]
Hi @nissim-dev , sorry for the delayed answer, i was taking a couple of days of.

I added the MyAppGlobalLoaderOverlay on the example project. It's a commom use of the GlobalLoaderOverlay widget.

Let me know if it does not fill your needs.

Thanks for using this package.

I'll close this issue for now, but feel free to reopen it with you need.

**Comment by nissim-dev** [comment]
Hi @rodrigobastosv , thanks for the feedback.

There was a different reason for which it wasn't working for me.

I was passing the context onto another dart class and was trying to access the `context.loaderOverlay` from the other class. I had imported  `loader_overlay.dart` on my `main.dart` but I hadn't imported it in the other class that I was using it in.

All i needed to do was import
`import 'package:loader_overlay/loader_overlay.dart';`

Maybe you should add this in the guide, it's a minor detail but others might have the same issue in the future.

**Comment by rodrigovasconceloszup** [comment]
Thanks very much for the feedback @nissim-dev . I'll update the documentation soon.

Thanks again for using this package :)
