### ISSUE TITLE
How i can show loading overlay when change to another screen

### ISSUE THREAD

**Issue by amasahara** [rodrigobastosv/loading_overlay#16]
I want show loading when opening page but don't know how to do it.
I try add it to initState but it not working.

```
void initState() {
    super.initState();
  context.loaderOverlay.show(widget: CustomLoadingWidget());
    Future.delayed(Duration(seconds: 3));
  }
```

**Comment by rodrigobastosv** [comment]
Hi @amasahara , thanks for using this package.

Try to put the same code on the didChangeDependencies method instead of initStat, that will probably work.

Something like this:

```
@override
 void didChangeDependencies() {
    super.didChangeDependencies();
    context.loaderOverlay.show(widget: CustomLoadingWidget());
    Future.delayed(Duration(seconds: 3));
 }
```

**Comment by amasahara** [comment]
thanks you for great package
