### ISSUE TITLE
Enhancement: set line break mode to title and message to Truncate Trail

### ISSUE THREAD

**Issue by alexrainman** [rodrigobastosv/loading_overlay#17]
Is it possible?
Need to keep the Snackbar same height, title and message in one line, no matter the amount of text.

**Comment by rodrigobastosv** [comment]
Hi @alexrainman, thanks for using this package.

You can pass to loaderOverlay whatever custom widget you need. So you can create your widget with the desired ui and call:

```
context.loaderOverlay.show(
  widget: YourCustomWidget()
);
```

**Comment by alexrainman** [comment]
Got i working. Thanks
