### ISSUE TITLE
[Request] A way to show/hide without depending on `context`

### ISSUE THREAD

**Issue by colbygarland** [rodrigobastosv/loading_overlay#18]
I would love to be able to show/hide this sucker anywhere, without depending on the context.

For example, if I am making some api calls, in my api class I would like to show/hide automatically. In this case, the code isn't in the widget, it is just in a dart file.

Is this possible?

**Comment by rodrigobastosv** [comment]
Unfortunately this is not possible. This package makes use of InheritedWidget and essentially this type of Widget needs the context to be found.

I understand it's a breeze to be able to show a loading in any location, even one that doesn't have context, but should you really do that?

In my opinion, loading is tied to widgets and their states and not business rules, so in my point of view it makes more sense to be calling them within the widgets' build.

But if you really want to use that you can try to give your MaterialApp a navigatorKey and with this key you can access the context and then show or hide the loading.

Let me hear what you think about, so we can discuss more.

If this is a demand from several people, I can work in this direction to try to make this new feature available.

**Comment by rodrigobastosv** [comment]
@colbygarland , thanks for using this package. Would love to hear some feedback from you.

**Comment by colbygarland** [comment]
@rodrigobastosv using the navigatorKey is perfect, this is exactly what I need :D thank you!

I really like the simplicity with this package, you are doing a very good job with triaging issues as well (fastest reply I have gotten on an open-source package yet!)

Closing with the solution:

```dart
// Create a navigatorKey
final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

// Attach it to the MaterialApp
Widget build(BuildContext context) {
  // removed for brevity
  navigatorKey: navigatorKey,
}

// Use it where you want now
navigatorKey.currentContext!.loaderOverlay.show();
navigatorKey.currentContext!.loaderOverlay.hide();
```

**Comment by rodrigobastosv** [comment]
Thanks for the kind words @colbygarland !

So glad to hear that is working for you.

If I feel that your need is the same as that of several other people, I may even develop it within the package to have this additional feature.
