### ISSUE TITLE
SpinKit not animating

### ISSUE THREAD

**Issue by roddersuk** [rodrigobastosv/loading_overlay#20]
I'm trying to use a SpinKit animated spinner within a loading_overlay.
The spinner is shown OK but doesn't animate.

**Comment by roddersuk** [comment]
Well, I don't know what I did but its working now. Sorry to have troubled you.

**Comment by rodrigobastosv** [comment]
Hi @roddersuk. Thanks for using this package.

Glad to hear it's working fine.

I'll close this issue for now, but feel free to reopen if you need.
