### ISSUE TITLE
Overlay opacity does not work with GlobalLoaderOverlay

### ISSUE THREAD

**Issue by LostInDarkMath** [rodrigobastosv/loading_overlay#21]
Hi there,
the opacity value is ignored in case of a `GlobalLoaderOverlay`. I tried with `useDefaultLoading: false,` and `useDefaultLoading: true,` but in both cases the `overlayOpacity` seems to have no effect.

**Comment by rodrigobastosv** [comment]
Thanks @LostInDarkMath for catching this one!
