### ISSUE TITLE
Se possível incluir um jeito de editar o botão de volta do Android dentro da própria widget LoaderOverlay

### ISSUE THREAD

**Issue by MisteriumEz** [rodrigobastosv/loading_overlay#23]
Salve, imaginei que tu fosse brasileiro somente pelo nome, mas aí vi os outros packages.

Utilizo bastante esse pacote aqui em especifico, e sempre coloco ele com um WillPopScope para poder travar o botão de volta, só abri o Issue para perguntar se seria possível adicionar um meio de você personalizar o botão de volta, como se fosse um parametro dentro da Widget LoaderOverlay, não sei se é possível, mas se for seria uma grande adição.

Abraço.

**Comment by rodrigovasconceloszup** [comment]
Oi @MisteriumEz , me parece uma boa feature!
Me da alguns dias que eu implemento isso.

**Comment by rodrigobastosv** [comment]
@MisteriumEz adicionei isso na versão 2.0.3. Já ta atualizado no pub.dev.

Muito obrigado por utilizar esse pacote!

**Comment by rodrigobastosv** [comment]
@MisteriumEz , precisei fazer um hotfix, então a versão 2.0.3 vai ter isso!
