### ISSUE TITLE
It doesn't prevent back button on android

### ISSUE THREAD

**Issue by putikorn** [rodrigobastosv/loading_overlay#24]
I can still use back button to go back when loader still showing.

**Comment by rodrigobastosv** [comment]
I'm aware of that. #23 is the exat same request as that. Give me a couple of days and i'll implement that

**Comment by rodrigobastosv** [comment]
Hi @putikorn , i've already implemented this. It's on 2.0.3 version, already on pub.dev.

Thanks a lot for using this package

**Comment by AErmek** [comment]
@rodrigobastosv  Hi!
thanks for package

I'm using 2.0.3v

`disableBackButton: true,`

`context.loaderOverlay.show(widget: const AppCenterLoading());`

didn't help me, what am I doing wrong?

**Comment by rodrigobastosv** [comment]
Helo @AErmek , thanks for using this package.

Can you provide a repository so i can reproduce this one?

**Comment by AErmek** [comment]
here i created new test project https://github.com/AErmek/flutter_project_tests/tree/main/flutter_tests

**Comment by rodrigobastosv** [comment]
Thanks a lot. Will definitely check this one later today

**Comment by rodrigobastosv** [comment]
Hello @AErmek , import the 2.0.4 version on your test project.

It will work :D

**Comment by AErmek** [comment]
Wow! it really worked, thank you so much! you fixed it very quickly, I appreciate it!
