### ISSUE TITLE
 Import implementation files from another package issue.

### ISSUE THREAD

**Issue by stasvo** [rodrigobastosv/loading_overlay#25]
By default development environment imports 'package:loader_overlay/src/overlay_controller_widget_extension.dart'  instead of 'package:loader_overlay/loader_overlay.dart' which is reason of [implementation_imports](https://dart-lang.github.io/linter/lints/implementation_imports.html) issue.

**Comment by rodrigobastosv** [comment]
Hi @stasvo , thanks a lot for using this package.

Yes, this is boring. I believe this is more of a problem with the auto import of the IDE than with the package itself. Flutter extensions still have difficulty importing extensions.

Your issue reminded to add a linter to the package tho, so i added flutter_lints to it.

Thanks very much!
