### ISSUE TITLE
Error : Bad state: Cannot add event after closing

### ISSUE THREAD

**Issue by dukesx** [rodrigobastosv/loading_overlay#26]
I am trying to use this by following methods: 

call context.loaderOverlay.show() in initState() as i start fetching async data then inside an async function that returns a Future, i call hide() function at the end before return. 

Problem is, that i am using GlobalOverlay (for named routes) and i am calling and hiding on demand. 

3 routes use this method. 2 routes work fine with each other. They call and hide fine but the third page/route is throwing this error and its beyond my understanding what mistake did i made.

**Comment by urvashik-7span** [comment]
Any luck on this? Facing same issue .

**Comment by rodrigobastosv** [comment]
Hi @urvashik-7span , thanks for using this package.

Are you calling overlay on initState? LoaderOverlay uses InheritwdWidget so you should never call it on initState.

Can you provide a small sample so i can reproduce your problem?

Thanks very much

**Comment by robmr88** [comment]
Hi! same issue

E/flutter ( 6847): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add event after closing
E/flutter ( 6847): #0      _StreamController.add (dart:async/stream_controller.dart:605:24)
E/flutter ( 6847): #1      OverlayControllerWidget.setOverlayVisible (package:loader_overlay/src/overlay_controller_widget.dart:29:28)
E/flutter ( 6847): #2      _OverlayExtensionHelper.show (package:loader_overlay/src/overlay_controller_widget_extension.dart:111:24)
E/flutter ( 6847): #3      _ProductsScreenState.build.<anonymous closure> (package:smart_order/screens/smartOrder/products_screen.dart:339:59)
E/flutter ( 6847): <asynchronous suspension>

**Comment by rodrigobastosv** [comment]
Hey @robmr88 , do you mind giving a minimal sample reproducing this issue? Will help a lot in the investigation.

**Comment by robmr88** [comment]
hi @rodrigobastosv , thanks for answering.
Actually I just solved it a couple of minutes ago.
The error was happening because I was using the GlobalLoaderOverlay over the MaterialApp in the root but
also I had LoaderOverlay inside some page inside the app.
Apparently they don't work together.
All worked well after I removed the inner LoaderOverlay from all the pages.
I think you should add the warning in the Basic Usage.
Thanks for the library 😁

**Comment by Kontrano** [comment]
> hi [@rodrigobastosv](https://github.com/rodrigobastosv) , thanks for answering. Actually I just solved it a couple of minutes ago. The error was happening because I was using the GlobalLoaderOverlay over the MaterialApp in the root but also I had LoaderOverlay inside some page inside the app. Apparently they don't work together. All worked well after I removed the inner LoaderOverlay from all the pages. I think you should add the warning in the Basic Usage. Thanks for the library 😁

Can confirm, was having this exact issue and also had a LoaderOverlay somewhere in addition to the Global and after removing it the error went away
