### ISSUE TITLE
[New Feature] Only show overlay over a portion of the screen (like only over ElevatedButton/Form)

### ISSUE THREAD

**Issue by mrishabh72** [rodrigobastosv/loading_overlay#27]
I am trying to show overlay only on one widget rather than the whole screen. I tried seperating that widget out, into a new widget but found no luck. Is my request possible to achieve?

I tried this, but still overlay occupies whole screen:
`class TapOnceButton extends StatelessWidget {
  final Widget child;
  final VoidFutureCallBack onPressed;

  const TapOnceButton({Key? key, required this.child, required this.onPressed})
      : super(key: key);
  @override
  Widget build(BuildContext context) => LoaderOverlay(
      child: ElevatedButton(
          child: this.child,
          onPressed: () async {
            context.loaderOverlay.show();
            await this.onPressed();
            context.loaderOverlay.hide();
          }));
}
`

**Comment by rodrigobastosv** [comment]
Hi @mrishabh72 , first of all, thanks a lot for using this package.

I'm currently a little busy, but I'll definitely take a look at your request. It seems to be a use case that makes sense. 

Please give me a few days that I try to see this for you.

Thanks!

**Comment by rodrigobastosv** [comment]
@mrishabh72, sorry for the late reply. 

I implemented your feature request. It should be available in version 2.0.5 already on pub.dev.

It was added 3 new properties to the `LoaderOverlay`:

- overlayWholeScreen: should be false in your case, to prevent the full screen "mode"
- overlayHeight: the desired height of the overlay
- overlayWidth: the desired width of the overlay

I also added an example called PartScreenOverlay on the example project to demonstrate this use. It shows a case of an overlay on an ElevatedButton.

Thanks a lor for using this package.

Will close this issue for now, but feel free to reopen if needed.
