### ISSUE TITLE
Loader overlay isn't showing when executing a 2nd time in initState

### ISSUE THREAD

**Issue by RaidenSora** [rodrigobastosv/loading_overlay#29]
Loader overlay is working fine when executed in initState for the first time using this code:
```
@protected
  @mustCallSuper
  void initState() {
    super.initState();
    WidgetsBinding.instance!.addPostFrameCallback((_) {
    context.loaderOverlay.show();
    });
  }
```

it checks first if the screen is fully loaded after executing the loaderOverlay.show(), this is working when the screen is loaded for the first time but the loading isn't showing when the screen is loaded and the initState is executed again. There is no error message or what so ever that's why I don't know what to do. Please help.

**Comment by rodrigobastosv** [comment]
Hi @RaidenSora , first of all thanks for using this package.

What do you mean by initState executing again? initState should never be executed twice on a widget lifecycle.

Also, it is not safe to call context.loaderOverlay.show() in the initState method. It is preferable that you call it on didChangeDependencies method.

Maybe this only change could make it work. Please let me know.

**Comment by RaidenSora** [comment]
What I mean by initState executing again is if I go to another screen a 2nd time.
home screen -> accounts screen -> home screen again
I didn't use Navigation.pop() on this to go back to home screen again.

**Comment by rodrigobastosv** [comment]
I got it now.

Did you tried to use didChangeDependencies method?

**Comment by RaidenSora** [comment]
I tried but it's not working too.

**Comment by rodrigobastosv** [comment]
Alright, can you please provide a sample repository so i can check it?

**Comment by RaidenSora** [comment]
I solved it, it's because of notifyListeners() of Provider that causing this strange bug. Thank you @rodrigobastosv for helping me.
