### ISSUE TITLE
Looking up a deactivated widget's ancestor is unsafe. To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by

### ISSUE THREAD

**Issue by kauemurakami** [rodrigobastosv/loading_overlay#3]
Estou com o mesmo problema hoje. creio que seja algo a ver com o "custom" ou context, quase certeza que é isso, mas tentei de tudo para escapar do erro com GlobalKey, extender stateless e estou perdido agora.
Estou tentando adicionar uma imagem em um container, vou expor um pouco de código aqui.
**stack**
```
`The following assertion was thrown while finalizing the widget tree:` // Esse erro pode ser resolvido deixando o LoaderOverlay dentro do Scaffold, mas na doc fala pra envolver o widget inteiro.
I/flutter (25412): Looking up a deactivated widget's ancestor is unsafe.
I/flutter (25412): At this point the state of the widget's element tree is no longer stable.
I/flutter (25412): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
I/flutter (25412): calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
I/flutter (25412): When the exception was thrown, this was the stack:
I/flutter (25412): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3825:9)
I/flutter (25412): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3839:6)
I/flutter (25412): #2      Element.findAncestorWidgetOfExactType (package:flutter/src/widgets/framework.dart:3931:12)
I/flutter (25412): #3      OverlayControllerWidget.of (package:loader_overlay/src/overlay_controller_widget.dart:10:15)
I/flutter (25412): #4      OverlayControllerWidgetExtension.getOverlayController (package:loader_overlay/src/overlay_controller_widget_extension.dart:8:31)
```

**main.dart**
```
GlobalLoaderOverlay(
      overlayColor: mainColor,
      overlayOpacity: 0.5,
      useDefaultLoading: false,
          child: GetMaterialApp(
        initialRoute: Routes.LANDING,
        initialBinding: LandingBinding(),
        home: LandingPage(),
        getPages: AppPages.pages,
        theme: appThemeData,
      ),
    )
```
**CadastroPage.dart** 
Aqui irei exibir o Loading, o fundo aparece com a cor customizada por mim no main, meu método cadastro funciona perfeitamente, o laoderoverlay é chamado, até mesmo fechado após o cadastro, mas a imagem não aparece e nem o CircularProgressIndicator . Após esse mostrarei meu widgetCustomLoading
```
class CadastroPage extends GetView<CadastroController> {
  static final GlobalKey formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return LoaderOverlay(
      overlayWidget: CustomLoading(message: 'Salvando informações, é rapidinho !'),
          useDefaultLoading: false,
          child: Scaffold(
            body: SafeArea(...
...
...
  CustomButtonWidget( 
                                    text: 'Registrar',
                                    callback: () async {
                                      final FormState form = formKey.currentState;
                                      if (form.validate()) {
                                        context.showLoaderOverlay();
                                        form.save();
                                        await controller.cadastrar();
                                        context.hideLoaderOverlay();
                                        Get.offAllNamed(Routes.HOME, arguments: controller.user);
                                      }
                                    },
                                  )
```

**CustomLoadingWidget**
```
import 'package:flutter/material.dart';

class CustomLoading extends Container {
  final String message;
  final Color color;
  CustomLoading({@required this.message, this.color = Colors.white});

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 300,
      width: 350,
      decoration: BoxDecoration(
        image:
            DecorationImage(image: AssetImage('assets/images/save_data.png'),fit: BoxFit.cover),
      ),
      child: CircularProgressIndicator(semanticsLabel: 'Estamos salvando seus dados, é rapidinho.',),
    );
  }
}

```
Como como devo envolver meus widgets, com rotas nomeadas de forma que eu possa usar um widget diferente para cada "LoaderOverlay" ou Page ? É o que estou tentando fazer.
O package possui limitações quanto a filhos internos, ou imagens, creio eu ser um problema de contexto, estou tentando tudo ao meu alcance e ainda não consegui :/  ? Espero ter ajudado, muitas pessoas devem estar passando pelo mesmo problema ao tentar isso.

_Originally posted by @kauemurakami in https://github.com/rodrigobastosv/loading_overlay/issues/2#issuecomment-666045469_

**Comment by rodrigobastosv** [comment]
@kauemurakami vou tentar reproduzir esse erro. Vou tentar retornar o mais breve possível

**Comment by rodrigobastosv** [comment]
@kauemurakami se você puder me mandar um repositório minimo com o erro ocorrendo ia me ajudar bastante :). Vi que você utiliza Get e não sou muito habituado com ele

**Comment by kauemurakami** [comment]
Deixei ele público, está um pouco diferente agora, até um minuto atrás estava conseguindo  exibir a imagem e o overlay ok com um **Future** como no exemplo, o problema é com a função async, ele apenas **abre** e **não fecha** agora, o problemas está sendo pra fechar e **só depois** navegar para outra rota nomeada, não sei como fazer isso,o **context** que uso no show nao consigo usar no hide.
Diretório do arquivo 
**lib > app > modules > cadastro** cadastro_page.dart e cadastro_controller.dart, mas creio que nada precisa ser feito no controller.
O widget que quero renderizar está em l**ib > app > widgets** custom_loading_widget.dart
[Repositório](https://github.com/kauemurakami/profectus) 
Agradeço desde já a sua atenção !

**Comment by rodrigobastosv** [comment]
Blz. Vou tentar trabalhar nisso hoje de noite

**Comment by kauemurakami** [comment]
Muito obrigado !!!

**Comment by rodrigobastosv** [comment]
@kauemurakami eu analisei a situação. Este package foi modelado para ter somente um Overlay global. Não é possível ter um LoaderOverlay para cada página. Isto é meio que uma limitação do próprio Flutter, como pegamos o overlay pelo contexto não tem como saber especificamente de qual vc vai querer pegar.

A ideia principal do package era ter um overlay global para poder ser chamado em todo o app. Realmente  um para cada página não é possível. Mas voce pode me dizer mais sobre pq precisa dele para cada página? Se você precisa de overlays diferentes para cada página talvez fosse melhor criar o código dentro de cada pagina. O que voce acha?

**Comment by kauemurakami** [comment]
Preciso pois vou mudar o texto e imagem de acordo com minha necessidade, tipo login é uma coisa salvar os dados é outra.
O problema q funciona se eu não sou pop.
Então se não posso usar o global widget pq vou o loaderoverlay diferente em várias paginas, tb n posso usar apenas o loaderOverlay em rotas nomeadas? 
No caso da pilha do erro atual, o que está ficando na árvore?
Tenho como conseguir a chave do overlay, isso ajudaria?
Entendi, vou tentar outras possibilidades, já vi o uso disso dessa forma em outros app, por isso estou tentando reproduzir.

**Comment by kauemurakami** [comment]
Consegui resolver dessa maneira, deixando como disse no global, funciona perfeitamente sem nenhum, talvez isso economize o tempo das pessoas que tentaram se aventurar como eu.
Irei marcar como fechada.

**Comment by rodrigobastosv** [comment]
Bug foi corrigido na versão 1.1.1!
