### ISSUE TITLE
Default Overlay Adaptive Loader

### ISSUE THREAD

**Issue by YalamberIngnam** [rodrigobastosv/loading_overlay#32]
Default overlay loader is set to circular progress indicator, provided by material.io by default. It also displays the same on IOS. can it be made adaptive?

**Comment by rodrigobastosv** [comment]
Hi @YalamberIngnam , first of all thanks for using this package and thanks for opening this issue.

It's a great request and fairly simple to do. By night i'll implement this. Thanks!

**Comment by YalamberIngnam** [comment]
Thank you.

**Comment by rodrigobastosv** [comment]
@YalamberIngnam your request was implemented on the 2.0.6 version of the package. It's already uploaded to pub.dev.

Thanks very much!
