### ISSUE TITLE
Feature Idea

### ISSUE THREAD

**Issue by jbryanh** [rodrigobastosv/loading_overlay#34]
Just an idea:  An optional timeout with duration to hide the loader.

**Comment by rodrigobastosv** [comment]
Hi @jbryanh , thanks for using this package. Can you provide more context? I found it interesting but i want to know the complete usecase of this. I tend not to like to bring features that can be implemented outside the package itself.

Thanks again

**Comment by rodrigobastosv** [comment]
Closing this issue due to the inactivity and the lack of response. Feel free to reopen if needed!

**Comment by jbryanh** [comment]
My sincerest apologies for ghosting this thread. How silly to request a feature and then not reply to your question, sorry I just got way past this note in my inbox.  

It's certainly fine to leave it off and leave it to the developer to create their own timeouts. As far as a use case, it could be anything. Classic case might be authentication...no error returned at auth, but a User isn't gotten, so the app doesn't proceed...just stuck spinning.

The most common cases are with bugs/errors that your code isn't handling, and instead of locking the app to the user, you can give it a timeout so they can try again, or at least continue in the app.  I thought of it because I mishandled an error, and when users encountered it, it was the equivalent to an app crash.  With a back up timeout, we can avoid that.
