### ISSUE TITLE
LateInitializationError when calling context.loaderOverlay

### ISSUE THREAD

**Issue by HoangNg97** [rodrigobastosv/loading_overlay#37]
Hi, personally I think this package is the most convenient option to create loading screen.
But i encounter an error while calling `context.loaderOverlay.hide()` or `context.loaderOverlay.show()` like below :

> Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: LateInitializationError: Field '_overlayController@416390500' has not been initialized.. Error thrown while handling a gesture.
>        at _OverlayExtensionHelper._overlayController(overlay_controller_widget_extension.dart)
>        at _OverlayExtensionHelper.hide(overlay_controller_widget_extension.dart:56)
>        at DialogUtils.showErrorDialog.<fn>.<fn>(dialog_utils.dart:230)
>        at _InkResponseState._handleTap(ink_well.dart:989)
>        at GestureRecognizer.invokeCallback(recognizer.dart:198)
>        at TapGestureRecognizer.handleTapUp(tap.dart:608)...

I knew it's because the late field `_overlayController`  has not been initialize yet.So, I think it's will be nice if you make it nullable instead or something which might help me to check it easier.

**Comment by rodrigobastosv** [comment]
@HoangNg97 thanks for using this package. Yeah i can just make it nullable and it will kind of fix your error, but i really want to know what's going on. Can you provide a small sample so i can reproduce here on my side?

**Comment by HoangNg97** [comment]
@rodrigobastosv Sorry for being late reply. I already made a small sample which may help you to acknowledge the error, please refer my sample here : [https://github.com/HoangNg97/demo-flutter](url)
I really hope you can fix this as soon as possible, my firebase crashlytics catch this as fatal error and give me crash-free users rate really low, which impact my user rating as well as the others

**Comment by rodrigobastosv** [comment]
Hey @HoangNg97 , so sorry, i guess i missed your reply. The error you are getting is because your `LoaderOverlay` is too low on the widget tree. It should be above `TabBarView`.

Can you give me access rights to your example repo, so i can create a pull request and you can see the solution. I tested here and it worked.

Sorry again for the late reply and thanks for using this package!

**Comment by HoangNg97** [comment]
Hi @rodrigobastosv , thanks a lot for your solution, i tried it and the error disappeared, you saved me and app crash-free users now skyrocket.
Thank you very much again and I hope your solution will help the others avoid this error
