### ISSUE TITLE
context.showLoaderOverlay() inside Cubit/Bloc

### ISSUE THREAD

**Issue by Alecckie** [rodrigobastosv/loading_overlay#4]
I am unable to call **context.showLoaderOverlay();** inside Cubit since it returns a widget.
Kindly guide on how this call should be made.
i.e
` if (state is LoginLoading) {
       //Return Loader layout here
	return _centerLoader();
  }`

**Comment by rodrigobastosv** [comment]
Hi @Alecckie , first of all thanks for using my package.
I do not quite get what you mean. 
I suposed you called this ```if (state is LoginLoading)``` inside a BlocBuilder right? There you have a context you can call.

Do you mind give me a small reproducible repository sample with this problem?

**Comment by Alecckie** [comment]
Good day sir, I was able to get it working, the issue was with my code and not with the package.
