### ISSUE TITLE
Missing features in GlobalLoaderOverlay

### ISSUE THREAD

**Issue by burghoffdavid** [rodrigobastosv/loading_overlay#41]
Hey, first of thanks for the package, works great! 
One thing I noticed is that the GlobalLoaderOverlay is missing some crucial features, such as `duration`, despite the documentation stating the following:

>To use this package with named routes you can just wrap your MaterialApp with GlobalLoaderOverlay. This widget has all the features of LoaderOverlay but it is provided for all the routes of the app

Is there currently a workaround to enable animations to the GlobalLoaderOverlay?

**Comment by rodrigobastosv** [comment]
Hey @burghoffdavid thanks a lot for using this package and thanks a lot for the feedback.

I'll take a look at this as soon as i can.

**Comment by rodrigobastosv** [comment]
Hello @burghoffdavid , i just added all the features of LoaderOverlay into GlobalLoaderOverlay.

It's already available at version 2.1.0 on pub.dev.

Thanks a lot for using this package.

I will close this issue for now, but feel free to reopen if needed.

**Comment by burghoffdavid** [comment]
Hey @rodrigobastosv! 
Wow that was fast, thanks for updating.

Cheers,
David
