### ISSUE TITLE
Loader Overlay acts weird when there's multiple pages using it

### ISSUE THREAD

**Issue by bruno-f-silva** [rodrigobastosv/loading_overlay#43]
Hello! First of all, I'd like to thank you for this great package!

Here's my problem. I have a hub page that has 5 buttons, 4 of them take you to different pages and one of them does stuff, part of it is to call context.loaderOverlay.show. When I click that button to show the overlay, it shows without any problem.

But if I go to any of the two of those four pages that also has a LoaderOverlay, go back to the hub page and click the button that shows the overlay, the context.loaderOverlay.visible shows true but the overlay doesn't show. AND if i click a second time on the button to show the overlay after it is hidden (even though it didn't show), it shows normally.

I have taken the LoaderOverlay from the widget tree of those two pages that have it and it works fine, but if I put it back, it acts like this.

I have tried many things. I have tried showing it and hiding it and showing it again, it doesn't work. I have tried using GlobalLoaderOverlay instead of LoaderOverlay and it doesn't work. I have taken every LoaderOverlay from every page and put GlobalLoaderOverlay on the main file, and it doesn't work. I'm not sure what to do. I'd appreciate if you could help me. Thanks!

**Comment by cabbi** [comment]
Have similar issue

**Comment by rodrigobastosv** [comment]
Hey guys, do any of you guys mind sharing a minimal example so i can take a look?

Loading Overlay uses InheritedWidget under the hooks, so i do not think this should be a issue?

Thanks very much!

**Comment by cabbi** [comment]
Hi, I did investigation in my code and I found out I was by mistake using GlobalLoaderOverlay more than once.
So I solved, thanks

**Comment by bruno-f-silva** [comment]
Hello! It seems I managed to solve the problem by trying GlobalLoaderOverlay once more! I'm guessing it had something to do with the many contexts...

Anyway, thank you for your help! And thanks once again for this package!

**Comment by adar2378** [comment]
Anyway to solve it without using GlobalLoaderOverlay? I have custom UI logic for different overlays. And I don't want to combine it all on the top level :(
