### ISSUE TITLE
The method 'setOverlayVisible' was called on null. Receiver: null Tried calling: setOverlayVisible(true)

### ISSUE THREAD

**Issue by mozaffari** [rodrigobastosv/loading_overlay#5]
loader_overlay: ^1.1.1
get: ^3.24.0
Get.context.showLoaderOverlay();

**Comment by rodrigobastosv** [comment]
Hi @mozaffari , that's interesting, never used loading_overlay with Getx, but give me a couple days to figure it out whats happening

**Comment by rodrigobastosv** [comment]
@mozaffari i found the problem. The get context is up o the widget tree from loader_overlay. So to use it with getx you have to make some adjustments. The above code snippet fixes this issue.

```
return Directionality(
      textDirection: TextDirection.ltr,
      child: LoaderOverlay(
        useDefaultLoading: true,
        child: GetMaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
            primarySwatch: Colors.blue,
            visualDensity: VisualDensity.adaptivePlatformDensity,
          ),
          home: MyHomePage(title: 'Flutter Demo Home Page'),
        ),
      ),
    );
```

You have to put `LoaderOverlay` widget above the GetMaterialApp and besides that you have to configure `Directionality` widget too.

Thanks for using this package, and feel free to ask more questions if that doesn't solve your problem

**Comment by mozaffari** [comment]
Wow!
forgot the interesting part of  GetX. 
fixed and marking the issue as closed.
