### ISSUE TITLE
Semi-transparent overlay not showing on iOS

### ISSUE THREAD

**Issue by lupusyon** [rodrigobastosv/loading_overlay#57]
Hello, I'm using GlobalLoaderOverlay in my app, but while the spinner icon is correctly shown, the overlay itself doesn't show on iOS (basically I only see the spinner without the semi-transparent background masking what's underneath). The only way for me to see it on iOS is to set overlayOpacity to 1, which of course is not what I want. The Android version works as intended. Any clues about something I might have missed?

**Comment by kirilllapshev** [comment]
I'm having the same issue

**Comment by merterkoc** [comment]
Could you use something like this?
Can you use something similar to this?
Use withOpacity in color
  ```
 return GlobalLoaderOverlay(
      overlayColor: Colors.black.withOpacity(0.8),
      child: MaterialApp(),
    );
```

**Comment by lupusyon** [comment]
@merterkoc thank you so much, I don't know how I didn't think of that. It works!

**Comment by merterkoc** [comment]
> @merterkoc thank you so much, I don't know how I didn't think of that. It works!

I'm glad your issue was resolved.  In the new version of flutter, the opacity widget does not work as it should on iOS devices.  We have hotfixed for this issue.  This fix will be reverted when Flutter fixes this issue
