### ISSUE TITLE
GlobalLoaderOverlay hide all content of the app

### ISSUE THREAD

**Issue by astudilloalex** [rodrigobastosv/loading_overlay#59]
![Screenshot_1694096473](https://github.com/rodrigobastosv/loading_overlay/assets/48831301/edd3f51b-b7b5-4e1a-b683-70a43973a826)
![Screenshot_1694096483](https://github.com/rodrigobastosv/loading_overlay/assets/48831301/f22c9c9d-f837-4eba-9417-4ffa957eee57)

Code:
```
Widget build(BuildContext context) {
    return GlobalLoaderOverlay(
      useDefaultLoading: false,
      overlayWidget: const Center(
        child: SpinKitCubeGrid(
          color: Colors.blue,
        ),
      ),
      child: MaterialApp.router(
        darkTheme: AppThemeData.dark,
        routerConfig: RoutePage.router,
        theme: AppThemeData.light,
        supportedLocales: AppLocalizations.supportedLocales,
        localizationsDelegates: AppLocalizations.localizationsDelegates,
      ),
    );
  }
```

**Comment by alaatm** [comment]
Same. It was working as of 2.3.0

**Comment by matheus85** [comment]
To get around this you can use:
overlayColor: Colors.black.withOpacity(0.4),

**Comment by astudilloalex** [comment]
> To get around this you can use: overlayColor: Colors.black.withOpacity(0.4),

Good answer
