### ISSUE TITLE
After loader hiding disabling tap events.

### ISSUE THREAD

**Issue by vmatiukh** [rodrigobastosv/loading_overlay#6]
When I hide loader, it disable all my buttons on screen. Can you help me to resolve this problem?

Logs:
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following StateError was thrown while handling a gesture:
Bad state: Cannot add event after closing

When the exception was thrown, this was the stack: 
#1      OverlayControllerWidget.setOverlayVisible (package:loader_overlay/src/overlay_controller_widget.dart:17:64)
#2      OverlayControllerWidgetExtension.showLoaderOverlay (package:loader_overlay/src/overlay_controller_widget_extension.dart:11:54)
#3      _SignInScreenState.sendSmsButtonWidget.<anonymous closure>.<anonymous closure> (package:app/screens/sign_in/sign_in_screen.dart:63:31)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#d9f33
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(73.7, 597.3)
  finalLocalPosition: Offset(58.7, 30.0)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by rodrigobastosv** [comment]
Hi @vmatiukh , first of all thanks for using this package. That seems quite strange.

Can you provide an example project to reproduce the error?

**Comment by vmatiukh** [comment]
Sorry, but I can't.  I am showing loader when I send request to server, after that I call hiding of keyboard

> FocusScope.of(context).unfocus(
                          disposition:
                              UnfocusDisposition.previouslyFocusedChild);
after that I call hide loader and push next screen. And when I pop screen back to previous screen I had error described before when I try to tap on button.

**Comment by rodrigobastosv** [comment]
Hello @vmatiukh , i was not able to reproduce this kind of behavior. It seems very strange to me and it's probably unrelated with this package. I'll keep this issue open a little more.

Any updates please send some feedback here
