### ISSUE TITLE
Feature request: Pass widget to showLoaderOverlay();

### ISSUE THREAD

**Issue by ivanesi** [rodrigobastosv/loading_overlay#7]
In our app we need to show different loaders - when app reconnecting, when user send invite to another user. So, it will be great if we can pass `overlayWidget` to `showLoaderOverlay()` like this:

`showLoaderOverlay(Text('Reconnecting'))` or `showLoaderOverlay(Text('Inviting'));`

**Comment by rodrigobastosv** [comment]
Hi @ivanesi , thanks for using this package!

That's a cool usecase, give me a few days to implement this.

**Comment by rodrigobastosv** [comment]
@ivanesi just pushed your suggestion to the 1.2.0 version. It's already availabe on pub.dev.

I've updated the README and the example to show how to use it. But it's basically what you have suggested :)

Thanks for the suggestion and thanks againg for using this package.
