### ISSUE TITLE
Theming GlobalLoaderOverlay

### ISSUE THREAD

**Issue by xErik** [rodrigobastosv/loading_overlay#74]
Is it possible to make `GlobalLoaderOverlay` respect the current Theme? 

I tried to use a Scaffold wrapped in a Theme that pulls its ThemeData from a global ThemeService. 

However, the dark / light themes did not get applied.

**Comment by rodrigobastosv** [comment]
Hey @xErik , thanks for using this package. `GlobalLoaderOverlay ` shouldn't interfere at all with Theme or ThemeData. `GlobalLoaderOverlay` just wraps the MaterialApp without affecting it.

**Comment by rodrigobastosv** [comment]
Thanks for the added context @xErik . I don't plan to bloat the API of the package adding this. Right now it's possible to switch this so i think it's better to not bring this responsibility to inside the package.
