### ISSUE TITLE
Request: Migrate to null-safety

### ISSUE THREAD

**Issue by cswkim** [rodrigobastosv/loading_overlay#8]
[This](https://dart.dev/null-safety/migration-guide) is the official Dart documentation on migrating to null-safety.

**Comment by rodrigobastosv** [comment]
Hi @cswkim , thanks for using this package.

Yeah, i'll try to migrate before Flutter Engage. Will leave the issue open until i end the migration.

**Comment by rodrigobastosv** [comment]
Just migrated the package to use null safety. It's available on the version 2.0.0-nullsafety.0 just releases on pub.dev.

Thanks @cswkim
