### ISSUE TITLE
loader_overlay requires Flutter SDK version >=3.27.0

### ISSUE THREAD

**Issue by yanashenyang** [rodrigobastosv/loading_overlay#83]
The current Flutter SDK version is 3.24.5.

Because project_xxx depends on loader_overlay >=5.0.0 which requires Flutter SDK version >=3.27.0, version solving failed.

You can try one of the following suggestions to make the pubspec resolve:
* Try using the Flutter SDK version: 3.27.1. 
* Consider downgrading your constraint on loader_overlay: flutter pub add loader_overlay:^4.0.4

why requires Flutter SDK version >=3.27.0 ???

**Comment by rodrigobastosv** [comment]
This issue was introduced in the 4.0.4 version due to the Flutter update for 3.27 version. To fix this problem please use the 4.0.4+1 version of the package or update your Flutter version to 3.27.

Please let me know if you encounter more issues

**Comment by yanashenyang** [comment]
oooook

**Comment by yanashenyang** [comment]
Please update the document
